os: Visual Studio 2015
environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
      PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - set ORIGPATH=%PATH%
  - ls C:/msys64/usr/bin
  - ls C:/msys64/usr/lib
  - ls C:/msys64/mingw64/bin
  - ls C:/msys64/mingw64/lib
  - where python
  - python -m pip install numpy # to avoid mkl
  - sh devtools/win/download_pytraj.sh

build_script:
  - echo "only build libcpptraj"
 
test_script:
  - set PATH=C:/msys64/usr/bin;C:/msys64/mingw64/bin;%PATH%
  - "sh -lc \"pacman -S --noconfirm --needed
      mingw-w64-x86_64-python2-numpy
    \""
  - sh devtools/win/download_pip.sh
  - python -m pip install notebook
