os: Windows Server 2012
environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
      PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"

install:
  - rmdir C:\cygwin /s /q
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - where python
  - python -m pip install numpy # to avoid mkl
  - sh devtools/win/download_pytraj.sh
  - ls pytraj
  - ls pytraj/core/*pyd
  - depends22_x86/depend.exe /oc:my.csv pytraj/core/topology_objects.pyd
  - cat my.csv

build_script:
  - echo "only build libcpptraj"
 
test_script:
  - echo "hello"
  - python -c "import numpy; print(numpy)"
  - python -c "import pytraj; pytraj.run_tests()"
