os: Windows Server 2012
environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
      PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"

install:
  - rmdir C:\cygwin /s /q
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - ls C:/msys64/usr/bin
  - ls C:/msys64/usr/lib
  - ls C:/msys64/mingw64/bin
  - ls C:/msys64/mingw64/lib
  - where python
  - python -m pip install numpy # to avoid mkl
  - sh devtools/win/download_pytraj.sh
  - sh devtools/win/download_dependencywalker.sh
  - cp C:/msys64/usr/lib/libpython2.7.dll.a pytraj/
  - cp C:/msys64/mingw64/bin/libgcc_s_seh-1.dll pytraj/
  - cp C:/msys64/mingw64/bin/libstdc++-6.dll pytraj/
  - ls pytraj
  - ls pytraj/core/*pyd
  # - depends.exe /oc:my.csv pytraj/core/topology_objects.pyd
  # - cat my.csv

build_script:
  - echo "only build libcpptraj"
 
test_script:
  - echo "hello"
  - python -c "import numpy; print(numpy)"
  - C:/msys64/mingw64/bin/python -c "import pytraj; pytraj.run_tests()"
  - python -c "import pytraj; pytraj.run_tests()"
